// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh36SN8NuzCNVzYBSgug3XCL9-rZ_VxkA',
    appId: '1:426064462200:web:c4d6c7f0758bea0156088d',
    messagingSenderId: '426064462200',
    projectId: 'mindbloom-5e780',
    authDomain: 'mindbloom-5e780.firebaseapp.com',
    storageBucket: 'mindbloom-5e780.firebasestorage.app',
    measurementId: 'G-QZRNJXD0EK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1JIP-JmsBV6Z25Rg0XuySUjbmdSMDs7Q',
    appId: '1:426064462200:android:2cc34df9c5d974e656088d',
    messagingSenderId: '426064462200',
    projectId: 'mindbloom-5e780',
    storageBucket: 'mindbloom-5e780.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALAUXYnSXA6gHdbosNF6oQkY-W6GP45kg',
    appId: '1:426064462200:ios:0d85f0cb9539262656088d',
    messagingSenderId: '426064462200',
    projectId: 'mindbloom-5e780',
    storageBucket: 'mindbloom-5e780.firebasestorage.app',
    iosBundleId: 'com.example.mindbloomFixed',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALAUXYnSXA6gHdbosNF6oQkY-W6GP45kg',
    appId: '1:426064462200:ios:0d85f0cb9539262656088d',
    messagingSenderId: '426064462200',
    projectId: 'mindbloom-5e780',
    storageBucket: 'mindbloom-5e780.firebasestorage.app',
    iosBundleId: 'com.example.mindbloomFixed',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh36SN8NuzCNVzYBSgug3XCL9-rZ_VxkA',
    appId: '1:426064462200:web:ebea242cf3d4641556088d',
    messagingSenderId: '426064462200',
    projectId: 'mindbloom-5e780',
    authDomain: 'mindbloom-5e780.firebaseapp.com',
    storageBucket: 'mindbloom-5e780.firebasestorage.app',
    measurementId: 'G-XLGF9XH8RG',
  );
}
